version: 2.1 

 

jobs: 

  build-and-test-and-lint:  

    machine: 

      image: ubuntu-2004:current       

    steps: 

      - checkout 

      - run: make deps

      - run: make lint 

      - run: make test     

  docker-build:  

    machine: 
      image: ubuntu-2004:current
      docker_layer_caching: true
    
    steps: 

      - checkout 
      - run: make docker_build
      - run: make docker_push


workflows: 

  basic:  

    jobs: 

      - build-and-test-and-lint
      - docker-build
