version: 2.1 

 

jobs: 

  build-and-test-and-lint:  

    machine: 

      image: ubuntu-2004:current       

    steps: 

      - checkout 

      - run: make deps

      - run: make lint 

      - run: make test     

  docker-build:  

    machine: 

      image: ubuntu-2004:current
    
    steps: 
    
      - checkout 
      - run: docker_build


workflows: 

  basic:  

    jobs: 

      - build-and-test-and-lint
      - docker-build
